### ISSUE TITLE
Single newline at the end of template adds multiple newlines when inserted

### ISSUE THREAD

**Issue by DanKaplanSES** [Briskine/briskine#480]
#### Description

If my template ends in a newline, it inserts two in the Gmail body. Note that I have a signature in my emails, and this might be relevant to reproduction.

#### Steps to reproduce:

1. Create a template like this: 
![image](https://user-images.githubusercontent.com/373675/190354233-4ed65f65-9426-4b34-ba71-08fc023cdb3c.png)
1. Compose an email
2. Click on the body to focus it (click on the first line)
3. Type your template and expand it

Expected:
One newline between the template and its signature
![image](https://user-images.githubusercontent.com/373675/190355121-53502580-2006-4b58-8204-c75a55de0d17.png)

Actual:
Two newlines between the template and its signature
![image](https://user-images.githubusercontent.com/373675/190354924-1cf51a9d-d82d-4873-bb2c-b687f925c914.png)

Note: removing the newline from the end of the template doesn't fix the problem, it introduces another problem:
![image](https://user-images.githubusercontent.com/373675/190355640-5a5c2ef5-73a7-464e-af90-50cbf85c2967.png)
There doesn't seem to be a way to add a single newline at the end of the template.

#### Related tickets/Sentry events:

- I have a feeling that [this one](https://github.com/Briskine/briskine/issues/3) introduced it, but it's a total stab in the dark

**Comment by ghinda** [comment]
Hi there,

I couldn't seem to be able to reproduce this issue. Adding a newline after the last line in the template moves the cursor to the next line when the templates is inserted - like in your expected result.

Could you please reach out on our support email address (support@briskine.com) with your more details (like your account email and the template with the issue)?
We do have a post-template-save HTML parser that cleans up the HTML and handles newlines (like turning empty `div`s into `br`s), so there could be an edge case with your template's HTML.

**Comment by ghinda** [comment]
I think we finally caught this. It seems the extra newline was there only when inserting templates with the dialog, in a contenteditable. 
Fixed on the latest version `7.6.2`.

**Comment by DanKaplanSES** [comment]
I am still experiencing this as described, and I am using 7.6.2 in firefox. 

Here are my signature settings: 

![image](https://user-images.githubusercontent.com/373675/207473213-8d3f82d1-ffac-4519-8f40-e2410686b06f.png)

This is what it looks like when I create a new message (the red line indicates where I place my cursor):

![image](https://user-images.githubusercontent.com/373675/207473471-493cfeb5-dfcb-4a4a-8647-3a2f950af64e.png)

I have a template `f` that looks like this (I highlighted the body to show that there is no newline at the end.):

![image](https://user-images.githubusercontent.com/373675/207473705-58d46755-57ed-41f2-8193-2ada2682c003.png)

If I type `f`, `tab`, it expands like this:

![image](https://user-images.githubusercontent.com/373675/207473819-092d2c33-c8b4-46c4-931e-b28b9e2c80d8.png)

If I put a newline at the end of the template like so (oops, just noticed that "select all" doesn't select the newline. To prove a newline is there, I've captured my actual cursor in the screenshot):

![image](https://user-images.githubusercontent.com/373675/207474065-5409e3c4-8174-43b5-9998-3c4a42e73912.png)

And if I expand that template on a brand-new email body, it looks like this:

![image](https://user-images.githubusercontent.com/373675/207474164-2e7c8803-60c4-4533-b579-bd46c4ea7858.png)

I can't find a way to have a single newline between the template and the signature.

I've done all the steps from scratch with a Gmail account that never had a signature before. I also tried doing this in a private tab where only Briskine, ublock origin, and Tampermonkey (with no active userscripts) were the only enabled extensions and it works the same way.

**Comment by ghinda** [comment]
Thanks for testing this, and the write-up.
Can you please test inserting templates with the dialog - instead of `shorcut+tab`? You can open the dialog with `ctrl+space` by default.

Any chance you could also test this on Chrome?

**Comment by DanKaplanSES** [comment]
There was no difference when I used `ctrl+space+left click`. 

There was no difference when I tried with chrome. Briskine wasn't installed on chrome, so I installed it to test it.
